--import Mathlib.MeasureTheory.Measure.MeasureSpace
--import Mathlib.Topology.MetricSpace.Basic
--import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
--import Mathlib.MeasureTheory.Measure.Typeclasses.Probability
--import Mathlib.Data.Real.Basic
--import Mathlib.Data.NNReal.Defs
--
--open MeasureTheory NNReal
--
--variable {X Y : Type*} [MeasurableSpace X] [MeasurableSpace Y]
--variable (μ ν : Measure X) [IsProbabilityMeasure μ] [IsProbabilityMeasure ν]
--
--def TransportPlans : Set (Measure (X × X)) :=
--  { π | Measure.map Prod.fst π = μ ∧ Measure.map Prod.snd π = ν }
--
--/-- Total cost of a transport plan `π` with respect to cost function `c`. -/
--noncomputable def totalCost (c : X × Y → ℝ≥0) (π : Measure (X × Y)) : ℝ≥0 :=
--  ∫⁻ xy, c xy ∂π
--
